worker_processes  1;
pid /Users/billchow/Documents/智慧冷冻站/scripts/nginx.scene.local.pid;

events {
    worker_connections  1024;
}

http {
    include       /opt/homebrew/etc/nginx/mime.types;
    default_type  application/octet-stream;
    access_log    /Users/billchow/Documents/智慧冷冻站/scripts/nginx.scene.local.access.log;
    error_log     /Users/billchow/Documents/智慧冷冻站/scripts/nginx.scene.local.error.log;
    sendfile      on;
    keepalive_timeout  65;

    server {
        listen       4000;
        server_name  127.0.0.1 localhost;
        sub_filter_once off;
        sub_filter_types text/xml application/xml application/json application/javascript text/javascript;
        sub_filter "http://192.168.110.250:8098" "http://127.0.0.1:8098";
        sub_filter "https://ln.szgreenenergy.com:3000/" "http://127.0.0.1:3001/";
        sub_filter "https://ln.szgreenenergy.com:3000" "http://127.0.0.1:3001";

        location = /3d/floor/eleven {
            return 301 /3d/floor/eleven/;
        }

        location /3d/floor/eleven/ {
            alias  /Users/billchow/Documents/126lnoffice/web/3d_build/floor11/build/;
            index  index.html index.htm;
        }

        location = /3d/floor/ten {
            return 301 /3d/floor/ten/;
        }

        location /3d/floor/ten/ {
            alias  /Users/billchow/Documents/126lnoffice/web/3d_build/floor10/build/;
            index  index.html index.htm;
        }

        location = /2d/floor/eleven {
            return 301 /2d/floor/eleven/;
        }

        location /2d/floor/eleven/ {
            alias  /Users/billchow/Documents/126lnoffice/web/2d_dist/floor11/html/;
            index  index.html index.htm;
        }

        location = /2d/floor/ten {
            return 301 /2d/floor/ten/;
        }

        location /2d/floor/ten/ {
            alias  /Users/billchow/Documents/126lnoffice/web/2d_dist/floor10/html/;
            index  index.html index.htm;
        }
    }
}
